# Generated by Django 2.1.5 on 2019-01-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('buy_unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sell_unit_cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='UnitLookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='materialtype',
            name='buy_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.UnitLookup'),
        ),
    ]
