# Generated by Django 2.1.5 on 2019-01-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventorySystem', '0002_auto_20190120_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prepared_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expiration_date', models.DateField()),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.MaterialType')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventorySystem.Restaurant'),
        ),
    ]
